### ISSUE TITLE
.parse() fails when line contains only a comment

### ISSUE THREAD

**Issue by enure** [decadecity/css-specificity-map#2]
```css
html {
  font-family: sans-serif;
  /* 1 */
  -ms-text-size-adjust: 100%;
  /* 2 */
  -webkit-text-size-adjust: 100%;
  /* 2 */
}
```

Running `parse()` on the code block above from normalize.css throws the following error: `TypeError: Cannot call method 'indexOf' of undefined` because it finds no value on that line... only a comment.

This change in `src/index.js` will fix the issue:

```diff
- if (!important && rule.value.indexOf('!important') > -1) {
+ if (!important && rule.value && rule.value.indexOf('!important') > -1) {
    important = true;
}
```
